### ISSUE TITLE
The was a problem decoding decoding this CoreML document - validator error: unable to deserialize object

### ISSUE THREAD

**Issue by spacegoodies** [huggingface/swift-coreml-transformers#15]
In the Resources folder, the .mlmodel files create the issue "validator error: unable to deserialize object" when building on Xcode 11.2.1.

**Comment by hollance** [comment]
Works fine here. Are you using the version from master? 

What is the full error message?

**Comment by jbmaxwell** [comment]
Same issue here. Xcode 11.3.1, macOS 10.15.3.
`coremlc: Error: unable to read document: /Users/jbmaxwell/Documents/xcode/swift-coreml-transformers/Resources/distilbert-squad-384_FP16.mlmodel
detail: validator error: unable to deserialize object
Command CoreMLModelCodegen failed with a nonzero exit code`
That is when I try to build. Clicking on any of the mlmodel files will give the "validator error".

**Comment by hollance** [comment]
Just out of curiosity, how many bytes is that "distilbert-squad-384_FP16.mlmodel" file on your system?

**Comment by jbmaxwell** [comment]
134 bytes... actually, they're all 134 bytes. That seems... uh.... odd? ;-)
I see that it's 172 mb on GitHub. Downloading directly it does validate (probably pretty obvious).

I have tried deleting and re-cloning, cleaning, deleting derived data, etc.

**Comment by hollance** [comment]
Did you install `git-lfs`?

**Comment by jbmaxwell** [comment]
ah... I don't believe I have (I mostly use my Ubuntu box for python stuff...). Will do!
UPDATE: Okay, `git lfs fetch` and everything's clearly downloading now. Thanks.

**Comment by julien-c** [comment]
Thanks so much for helping @hollance
