### ISSUE TITLE
What GPT-2 model is distilled here?

### ISSUE THREAD

**Issue by philipkd** [huggingface/swift-coreml-transformers#19]
Is it the gpt2-small (124M), gpt2-medium (345M), gpt2-large (774M), or the gpt-xl (1.5B) that this implementation uses out of the box?

**Comment by julien-c** [comment]
It's the small one, from https://huggingface.co/gpt2

**Comment by anentropic** [comment]
What do the numbers in the filenames of the mlmodel files represent?

- [`gpt2-64-12.mlmodel`](https://github.com/huggingface/swift-coreml-transformers/blob/master/Resources/gpt2-64-12.mlmodel)
- [`gpt2-256.mlmodel`](https://github.com/huggingface/swift-coreml-transformers/blob/master/Resources/gpt2-256.mlmodel)
- [`gpt2-512.mlmodel`](https://github.com/huggingface/swift-coreml-transformers/blob/master/Resources/gpt2-512.mlmodel)

I thought the usual GPT2 sizes were: 124M, 355M, 774M, and 1.5B... Not sure how these correspond.

Is `gpt2-64-12.mlmodel` smaller (parameters) than `gpt2-256.mlmodel`?  The size on disk is bigger.

**Comment by anentropic** [comment]
Well, I asked ChatGPT... no idea if this plausible-sounding info is correct or just hallucinated:

> These configurations are not directly equivalent to the conventional way of specifying GPT-2 model sizes.
> 
> However, there is some correspondence between the configurations of the `.mlmodel` files and the conventional GPT-2 model sizes. Specifically:
> 
> - The `gpt2-64-12.mlmodel` file corresponds to a smaller GPT-2 model than the conventional "small" size, which has 124 million parameters. The `gpt2-64-12.mlmodel` file has fewer parameters than the "small" model, with only 51 million parameters.
> - The `gpt2-256.mlmodel` file corresponds roughly to the "medium" size GPT-2 model, which has 355 million parameters. The `gpt2-256.mlmodel` has 167 million parameters.
> - The `gpt2-512.mlmodel` file corresponds roughly to the "large" size GPT-2 model, which has 774 million parameters. The `gpt2-512.mlmodel` has 341 million parameters.

From this is seems that `gpt2-64-12` is smaller than any of the Open AI GPT2 models on Huggingface, `gpt2-256` is a little bigger than the base 124M GPT2, and `gpt2-512` is similar to GPT2-medium ?
