### ISSUE TITLE
Unable to deserialize object

### ISSUE THREAD

**Issue by markvanwijnen** [huggingface/swift-coreml-transformers#26]
I run xCode 13.2.1. When I build and run I get the following warnings, which results in errors.

```
coremlc: warning: unable to read document: /Users/name/Downloads/swift-coreml-transformers-master/Resources/gpt2-64-12.mlmodel
detail: validator error: unable to deserialize object
coremlc: error: unable to read document: /Users/name/Downloads/swift-coreml-transformers-master/Resources/gpt2-64-12.mlmodel
detail: validator error: unable to deserialize object
```
`
unable to read document: /Users/name/Downloads/swift-coreml-transformers-master/Resources/gpt2-64-12.mlmodel
unable to read document: /Users/name/Downloads/swift-coreml-transformers-master/Resources/distilgpt2-64-6.mlmodel
`

**Comment by markvanwijnen** [comment]
Let me answer it myself. This has to do with GIT Large File Storage. 

Hopefully this will help out others:

- Make sure to clone the GIT repository.
- Use the command: git lfs install
- Use the command: git lfs fetch
- Use the command: git lfs checkout

Not sure if that last one is needed, but with this it worked.

**Comment by frederikbrammer** [comment]
The last command `git lfs checkout`is indeed needed to move the model files to the correct location.
