### ISSUE TITLE
GPT2-large

### ISSUE THREAD

**Issue by kpacholak** [huggingface/swift-coreml-transformers#35]
Hi!
Do you know, how can I get gpt2-large version? 
is it as simple as change 
`model_name = "gpt2"`
to 
`model_name = "gpt2-large"`
in [Python converting script](https://github.com/huggingface/swift-coreml-transformers/blob/master/model_generation/gpt2.py)?

**Comment by julien-c** [comment]
you should use this newer tool: https://huggingface.co/spaces/huggingface-projects/transformers-to-coreml

cc @pcuenca
