### ISSUE TITLE
Error when building the gpt2 app

### ISSUE THREAD

**Issue by bilal2vec** [huggingface/swift-coreml-transformers#9]
The BERT app works fine, but it looks like there is something wrong with the .mlmodel files for gpt2.

Xcode is giving me this error when building the gpt2 app:

```
Showing All Issues
CoreMLModelCompile /Users/[user]/Library/Developer/Xcode/DerivedData/CoreMLBert-dgdnlbjylimukwhbaciwiwfltdzp/Build/Products/Debug-iphoneos/CoreMLGPT2.app/ 

/Users/[user]/Desktop/swift-coreml-transformers/Resources/gpt2-512.mlmodel (in target 
'CoreMLGPT2' from project 'CoreMLBert')

    cd /Users/[user]/Desktop/swift-coreml-transformers

    /Applications/Xcode.app/Contents/Developer/usr/bin/coremlc compile 

/Users/[user]/Desktop/swift-coreml-transformers/Resources/gpt2-512.mlmodel 

/Users/[user]/Library/Developer/Xcode/DerivedData/CoreMLBert-

dgdnlbjylimukwhbaciwiwfltdzp/Build/Products/Debug-iphoneos/CoreMLGPT2.app/ --output-
partial-info-plist /Users/[user]/Library/Developer/Xcode/DerivedData/CoreMLBert-dgdnlbjylimukwhbaciwiwfltdzp/Build/Intermediates.noindex/CoreMLBert.build/Debug-iphoneos/CoreMLGPT2.build/gpt2-512-CoreMLPartialInfo.plist

coremlc: Error: Error reading protobuf spec. validator error: Bias layer '0_block_attn_afterbias' cannot be 2 dimensional. Must be 1D or 3D.

Command CoreMLModelCompile failed with a nonzero exit code
```

IOS version: 13.1 public beta 3
Xcode version: 11

**Comment by julien-c** [comment]
This is a known issue since Xcode 11 GM (we used Xcode 11 Betas) also reported by @hollance

Are you on Catalina or Mojave?

We'll need to re-run the network building script with an updated shape for this layer

**Comment by datctbk** [comment]
I have the same issue, i used Mojave, XCode 11.
Do you have solution @julien-c ?
Thanks

**Comment by hollance** [comment]
You can fix the issues in the model using the following Python script:

```
# or gpt2-512.mlmodel
model = coremltools.models.MLModel("gpt2-64-12.mlmodel") 

spec = model._spec
nn = spec.neuralNetwork
layer_dict = {l.name:i for i,l in enumerate(nn.layers)}

layer_names = [
    "0_block_attn_afterbias",
    "1_block_attn_afterbias",
    "2_block_attn_afterbias",
    "3_block_attn_afterbias",
    "4_block_attn_afterbias",
    "5_block_attn_afterbias",
    "6_block_attn_afterbias",
    "7_block_attn_afterbias",
    "8_block_attn_afterbias",
    "9_block_attn_afterbias",
    "10_block_attn_afterbias",
    "11_block_attn_afterbias",
]

for name in layer_names:
    layer = nn.layers[layer_dict[name]]
    layer.bias.shape.extend([layer.bias.shape[-1]])
    layer.bias.shape[0] = 1

coremltools.utils.save_spec(spec, "gpt2-64-12-NEW.mlmodel")  
```

**Comment by hollance** [comment]
My iPhone XS does about 2.3 tokens / sec by the way.

**Comment by julien-c** [comment]
That's awesome @hollance! 🤗 🤗 🤗 

I think the root issue is fixable by changing this line's shape:
https://github.com/huggingface/swift-coreml-transformers/blob/master/model_generation/gpt2.py#L207

Also would you be able to upload your weights inside the repo (replacing the old ones – I'm adding you as an editor right now)?

**Comment by hollance** [comment]
OK done. :-)

**Comment by julien-c** [comment]
I'll keep the issue open as a reminder to fix the `model_generation` script line as well.

Thank you!

**Comment by bilal2vec** [comment]
Would changing the line from:

```shape_bias=[sequence_length, sequence_length]```

to

```shape_bias=[1, sequence_length, sequence_length]```

fix the issue?

**Comment by hollance** [comment]
@bkkaggle That seems correct. That's exactly the change I made in the mlmodel file.

**Comment by bilal2vec** [comment]
I made a [pull request](https://github.com/huggingface/swift-coreml-transformers/pull/10) that should solve this issue

What version of pytorch do you use for this repository? I'm getting this error when running `python gpt2.py` to see if the updated code works:

```
0
Traceback (most recent call last):
  File "gpt2.py", line 77, in <module>
    ln_epsilon = model.h[i].ln_1.variance_epsilon
  File "/home/bilal/miniconda3/envs/swift/lib/python3.7/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'LayerNorm' object has no attribute 'variance_epsilon'
```

It looks like the script is looking for a attribute that no longer exists in nn.LayerNorm.

Also, in your conversion scripts (https://github.com/huggingface/swift-coreml-transformers/blob/master/model_generation/gpt2.py#L9), you still refer to the `pytorch_transformers` package. Should I open an issue to update the files and requirements.txt to the new [transformers](https://github.com/huggingface/transformers) package/repo ?

**Comment by julien-c** [comment]
That'd be awesome! `variance_epsilon` should just be `eps` now (we used to have a custom LayerNorm implem from back when it wasn't implemented in torch)

**Comment by bilal2vec** [comment]
This should be fixed once (https://github.com/huggingface/swift-coreml-transformers/pull/11) is merged in.

**Comment by julien-c** [comment]
Thanks!
